using System.ComponentModel.DataAnnotations;

namespace Market.Domain.Enums;

public enum Country
{
    Afghanistan,
    Albania,
    Algeria,
    Andorra,
    Angola,
    [Display(Name = "Antigua and Barbuda")]
    AntiguaAndBarbuda,
    Argentina,
    Armenia,
    Australia,
    Austria,
    Azerbaijan,
    Bahamas,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Benin,
    Bhutan,
    Bolivia,
    [Display(Name = "Bosnia and Herzegovina")]
    BosniaAndHerzegovina,
    Botswana,
    Brazil,
    Brunei,
    Bulgaria,
    [Display(Name = "Burkina Faso")]
    BurkinaFaso,
    Burundi,
    [Display(Name = "Cape Verde")]
    CapeVerde,
    Cambodia,
    Cameroon,
    Canada,
    [Display(Name = "Central African Republic")]
    CentralAfricanRepublic,
    Chad,
    Chile,
    China,
    Colombia,
    Comoros,
    Congo,
    [Display(Name = "Costa Rica")]
    CostaRica,
    Croatia,
    Cuba,
    Cyprus,
    [Display(Name = "Czech Republic")]
    CzechRepublic,
    [Display(Name = "Democratic Republic of the Congo")]
    DemocraticRepublicOfTheCongo,
    Denmark,
    Djibouti,
    Dominica,
    [Display(Name = "Dominican Republic")]
    DominicanRepublic,
    Ecuador,
    Egypt,
    [Display(Name = "El Salvador")]
    ElSalvador,
    [Display(Name = "Equatorial Guinea")]
    EquatorialGuinea,
    Eritrea,
    Estonia,
    Eswatini,
    Ethiopia,
    Fiji,
    Finland,
    France,
    Gabon,
    Gambia,
    Georgia,
    Germany,
    Ghana,
    Greece,
    Grenada,
    Guatemala,
    Guinea,
    [Display(Name = "Guinea-Bissau")]
    GuineaBissau,
    Guyana,
    Haiti,
    Honduras,
    Hungary,
    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland,
    Israel,
    Italy,
    Jamaica,
    Japan,
    Jordan,
    Kazakhstan,
    Kenya,
    Kiribati,
    Kuwait,
    Kyrgyzstan,
    Laos,
    Latvia,
    Lebanon,
    Lesotho,
    Liberia,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Madagascar,
    Malawi,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    [Display(Name = "Marshall Islands")]
    MarshallIslands,
    Mauritania,
    Mauritius,
    Mexico,
    Micronesia,
    Moldova,
    Monaco,
    Mongolia,
    Montenegro,
    Morocco,
    Mozambique,
    Myanmar,
    Namibia,
    Nauru,
    Nepal,
    Netherlands,
    [Display(Name = "New Zealand")]
    NewZealand,
    Nicaragua,
    Niger,
    Nigeria,
    [Display(Name = "North Korea")]
    NorthKorea,
    [Display(Name = "North Macedonia")]
    NorthMacedonia,
    Norway,
    Oman,
    Pakistan,
    Palau,
    Palestine,
    Panama,
    [Display(Name = "Papua New Guinea")]
    PapuaNewGuinea,
    Paraguay,
    Peru,
    Philippines,
    Poland,
    Portugal,
    Qatar,
    Romania,
    Russia,
    Rwanda,
    [Display(Name = "Saint Kitts and Nevis")]
    SaintKittsAndNevis,
    [Display(Name = "Saint Lucia")]
    SaintLucia,
    [Display(Name = "Saint Vincent and the Grenadines")]
    SaintVincentAndTheGrenadines,
    Samoa,
    [Display(Name = "San Marino")]
    SanMarino,
    [Display(Name = "Sao Tome and Principe")]
    SaoTomeAndPrincipe,
    [Display(Name = "Saudi Arabia")]
    SaudiArabia,
    Senegal,
    Serbia,
    Seychelles,
    SierraLeone,
    Singapore,
    Slovakia,
    Slovenia,
    [Display(Name = "Solomon Islands")]
    SolomonIslands,
    Somalia,
    [Display(Name = "South Africa")]
    SouthAfrica,
    [Display(Name = "South Korea")]
    SouthKorea,
    [Display(Name = "South Sudan")]
    SouthSudan,
    Spain,
    [Display(Name = "Sri Lanka")]
    SriLanka,
    Sudan,
    Suriname,
    Sweden,
    Switzerland,
    Syria,
    Taiwan,
    Tajikistan,
    Tanzania,
    Thailand,
    [Display(Name = "Timor-Leste")]
    TimorLeste,
    Togo,
    Tonga,
    [Display(Name = "Trinidad and Tobago")]
    TrinidadAndTobago,
    Tunisia,
    Turkey,
    Turkmenistan,
    Tuvalu,
    Uganda,
    Ukraine,
    [Display(Name = "United Arab Emirates")]
    UnitedArabEmirates,
    [Display(Name = "United Kingdom")]
    UnitedKingdom,
    [Display(Name = "United States")]
    UnitedStates,
    Uruguay,
    Uzbekistan,
    Vanuatu,
    [Display(Name = "Vatican City")]
    VaticanCity,
    Venezuela,
    Vietnam,
    Yemen,
    Zambia,
    Zimbabwe
}